// Package pb simulates a Protobuf-generated package.
//
// In a real project, this would be generated by protoc-gen-go.
// The key characteristics are:
//   - Field names follow Protobuf naming conventions (not Go conventions).
//   - Getter methods provide nil-safe access.
package pb

// User represents a Protobuf-generated user message.
type User struct {
	UserId    int64  `json:"user_id"`
	FullName  string `json:"full_name"`
	UserEmail string `json:"user_email"`
	UserAge   int32  `json:"user_age"`
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *User) GetUserAge() int32 {
	if x != nil {
		return x.UserAge
	}
	return 0
}
