// Code generated by goxmap; DO NOT EDIT.

package main

// MapEventToEventDTO maps Event to EventDTO.
func MapEventToEventDTO(src *Event) *EventDTO {
	if src == nil {
		return nil
	}
	dst := &EventDTO{}
	dst.ID = src.ID
	dst.Title = src.Title
	dst.Description = src.Description
	dst.StartTime = FormatTime(src.StartTime)
	dst.EndTime = FormatTime(src.EndTime)
	dst.Tags = NormalizeTags(src.Tags)
	return dst
}
