// Code generated by goxmap; DO NOT EDIT.

package main

// MapDBUserToUserResponse maps DBUser to UserResponse.
func MapDBUserToUserResponse(src DBUser) UserResponse {
	var dst UserResponse
	dst.ID = src.ID
	dst.FirstName = src.FirstName
	dst.LastName = src.LastName
	dst.Email = func() string {
		if src.Email != nil {
			return *src.Email
		}
		var zero string
		return zero
	}()
	dst.Phone = func() string {
		if src.Phone != nil {
			return *src.Phone
		}
		var zero string
		return zero
	}()
	dst.Age = src.Age
	dst.Active = src.Active
	return dst
}
