package generator

import (
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/hacks1ash/goxmap/internal/loader"
	"github.com/hacks1ash/goxmap/internal/matcher"
)

func testdataDir(t *testing.T) string {
	t.Helper()
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot determine test file path")
	}
	// Navigate from internal/generator/ to project root testdata/loader/.
	return filepath.Join(filepath.Dir(filename), "..", "..", "testdata", "loader")
}

func TestGenerate_DirectAssignment(t *testing.T) {
	cfg := Config{
		PackageName: "models",
		FuncName:    "MapUserToUserDTO",
		SrcType:     "User",
		DstType:     "UserDTO",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
			},
			{
				Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				Dst: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
			},
		},
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)

	assertContains(t, output, "// Code generated by goxmap; DO NOT EDIT.")
	assertContains(t, output, "package models")
	assertContains(t, output, "func MapUserToUserDTO(src *User) *UserDTO")
	assertContains(t, output, "dst.ID = src.ID")
	assertContains(t, output, "dst.Name = src.Name")
}

func TestGenerate_PointerDeref(t *testing.T) {
	cfg := Config{
		PackageName: "models",
		FuncName:    "MapAToB",
		SrcType:     "A",
		DstType:     "B",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "Value", TypeStr: "*string", ElemType: "string", IsPtr: true},
				Dst: loader.StructField{Name: "Value", TypeStr: "string", ElemType: "string", IsPtr: false},
			},
		},
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)
	assertContains(t, output, "src.Value != nil")
	assertContains(t, output, "*src.Value")
}

func TestGenerate_PointerAddr(t *testing.T) {
	cfg := Config{
		PackageName: "models",
		FuncName:    "MapAToB",
		SrcType:     "A",
		DstType:     "B",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "Value", TypeStr: "string", ElemType: "string", IsPtr: false},
				Dst: loader.StructField{Name: "Value", TypeStr: "*string", ElemType: "string", IsPtr: true},
			},
		},
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)
	assertContains(t, output, "v := src.Value")
	assertContains(t, output, "return &v")
}

func TestGenerate_CustomMapperFunc(t *testing.T) {
	cfg := Config{
		PackageName: "models",
		FuncName:    "MapAToB",
		SrcType:     "A",
		DstType:     "B",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "CreatedAt", TypeStr: "time.Time", ElemType: "time.Time"},
				Dst: loader.StructField{Name: "CreatedAt", TypeStr: "string", ElemType: "string", MapperFn: "FormatTime"},
			},
		},
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)
	assertContains(t, output, "dst.CreatedAt = FormatTime(src.CreatedAt)")
}

func TestGenerate_StructLevelMapper(t *testing.T) {
	cfg := Config{
		PackageName:    "models",
		FuncName:       "MapAToB",
		SrcType:        "A",
		DstType:        "B",
		StructMapperFn: "CustomMapAToB",
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)
	assertContains(t, output, "CustomMapAToB(*src)")
}

func TestGenerateMulti_NestedStruct(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	srcInfo, err := loader.LoadStructFromPkg(pctx, "User")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(User): %v", err)
	}

	dstInfo, err := loader.LoadStructFromPkg(pctx, "UserDTO")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(UserDTO): %v", err)
	}

	result := matcher.Match(srcInfo, dstInfo)

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapUserToUserDTO",
			SrcType:     "User",
			DstType:     "UserDTO",
			Pairs:       result.Pairs,
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should contain the root mapper.
	assertContains(t, output, "func MapUserToUserDTO(src *User) *UserDTO")

	// Should contain a nested mapper for Address.
	assertContains(t, output, "func MapAddressToAddressDTO(src *Address) *AddressDTO")

	// Should contain a nested mapper for EmailInfo.
	assertContains(t, output, "func MapEmailInfoToEmailInfoDTO(src *EmailInfo) *EmailInfoDTO")

	// The root mapper should call the nested mappers.
	assertContains(t, output, "MapAddressToAddressDTO(&src.Address)")

	// Should have a slice mapping loop for Emails.
	assertContains(t, output, "for i, v := range src.Emails")
	assertContains(t, output, "MapEmailInfoToEmailInfoDTO(&item)")
}

func TestGenerateMulti_NestedPtrStruct(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	srcInfo, err := loader.LoadStructFromPkg(pctx, "UserWithPtr")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(UserWithPtr): %v", err)
	}

	dstInfo, err := loader.LoadStructFromPkg(pctx, "UserWithPtrDTO")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(UserWithPtrDTO): %v", err)
	}

	result := matcher.Match(srcInfo, dstInfo)

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapUserWithPtrToUserWithPtrDTO",
			SrcType:     "UserWithPtr",
			DstType:     "UserWithPtrDTO",
			Pairs:       result.Pairs,
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should handle *Address -> AddressDTO with nil check (via inline func + nil pointer propagation).
	assertContains(t, output, "MapAddressToAddressDTO(src.Address)")
	assertContains(t, output, "var zero AddressDTO")
}

func TestGenerateMulti_MapperDiscovery(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	srcInfo, err := loader.LoadStructFromPkg(pctx, "User")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(User): %v", err)
	}

	dstInfo, err := loader.LoadStructFromPkg(pctx, "UserDTO")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(UserDTO): %v", err)
	}

	result := matcher.Match(srcInfo, dstInfo)

	// Simulate that MapAddressToAddressDTO already exists.
	existing := map[string]bool{
		"MapAddressToAddressDTO": true,
	}

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapUserToUserDTO",
			SrcType:     "User",
			DstType:     "UserDTO",
			Pairs:       result.Pairs,
		},
		ExistingMappers: existing,
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should still reference MapAddressToAddressDTO in the call.
	assertContains(t, output, "MapAddressToAddressDTO")

	// But should NOT generate a new MapAddressToAddressDTO function definition.
	if strings.Contains(output, "func MapAddressToAddressDTO") {
		t.Error("should not generate MapAddressToAddressDTO when it already exists in the package")
	}

	// Should still generate MapEmailInfoToEmailInfoDTO since it doesn't exist.
	assertContains(t, output, "func MapEmailInfoToEmailInfoDTO")
}

func TestGenerateMulti_CircularDependency(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	srcInfo, err := loader.LoadStructFromPkg(pctx, "Parent")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(Parent): %v", err)
	}

	dstInfo, err := loader.LoadStructFromPkg(pctx, "ParentDTO")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(ParentDTO): %v", err)
	}

	result := matcher.Match(srcInfo, dstInfo)

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapParentToParentDTO",
			SrcType:     "Parent",
			DstType:     "ParentDTO",
			Pairs:       result.Pairs,
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	// This should NOT hang or panic due to circular references.
	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should contain both mapper functions.
	assertContains(t, output, "func MapParentToParentDTO(src *Parent) *ParentDTO")
	assertContains(t, output, "func MapChildToChildDTO(src *Child) *ChildDTO")

	// Should reference the child mapper from parent.
	assertContains(t, output, "MapChildToChildDTO")
	// Should reference the parent mapper from child.
	assertContains(t, output, "MapParentToParentDTO")
}

func TestGenerateMulti_SingleFunction(t *testing.T) {
	// Test that GenerateMulti works for a simple case with no nesting.
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
					Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "package models")
	assertContains(t, output, "func MapAToB(src *A) *B")
	assertContains(t, output, "dst.ID = src.ID")
}

// --- Cross-package generation tests ---

func TestGenerateCross_ToExternalOnly(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:        "models",
		InternalType:       "User",
		ExternalType:       "UserProto",
		ExternalPkgName:    "pb",
		ExternalPkgPath:    "github.com/org/repo/proto",
		ToExternalFuncName: "MapUserToUserProto",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "UserId", TypeStr: "int", ElemType: "int"},
			},
			{
				Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				Dst: loader.StructField{Name: "DisplayName", TypeStr: "string", ElemType: "string"},
			},
		},
		Bidirectional: false,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)

	assertContains(t, output, "// Code generated by goxmap; DO NOT EDIT.")
	assertContains(t, output, "package models")
	assertContains(t, output, `"github.com/org/repo/proto"`)
	assertContains(t, output, "func MapUserToUserProto(src *User) *pb.UserProto")
	assertContains(t, output, "dst.UserId = src.ID")
	assertContains(t, output, "dst.DisplayName = src.Name")

	// Should NOT contain a reverse function.
	if strings.Contains(output, "MapUserProtoToUser") {
		t.Error("should not generate reverse function when Bidirectional=false")
	}
}

func TestGenerateCross_Bidirectional(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:          "models",
		InternalType:         "User",
		ExternalType:         "UserProto",
		ExternalPkgName:      "pb",
		ExternalPkgPath:      "github.com/org/repo/proto",
		ToExternalFuncName:   "MapUserToUserProto",
		FromExternalFuncName: "MapUserProtoToUser",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "UserId", TypeStr: "int", ElemType: "int"},
			},
		},
		FromExternalPairs: []matcher.FieldPair{
			{
				Src:        loader.StructField{Name: "UserId", TypeStr: "int", ElemType: "int"},
				Dst:        loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				UseGetter:  true,
				GetterName: "GetUserId",
			},
		},
		Bidirectional: true,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)

	// Should contain both functions.
	assertContains(t, output, "func MapUserToUserProto(src *User) *pb.UserProto")
	assertContains(t, output, "func MapUserProtoToUser(src *pb.UserProto) *User")

	// ToExternal should use direct field access.
	assertContains(t, output, "dst.UserId = src.ID")

	// FromExternal should use getter.
	assertContains(t, output, "src.GetUserId()")
}

func TestGenerateCross_WithGetters(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:          "models",
		InternalType:         "User",
		ExternalType:         "UserProto",
		ExternalPkgName:      "pb",
		ExternalPkgPath:      "github.com/org/repo/proto",
		ToExternalFuncName:   "MapUserToUserProto",
		FromExternalFuncName: "MapUserProtoToUser",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				Dst: loader.StructField{Name: "DisplayName", TypeStr: "string", ElemType: "string"},
			},
		},
		FromExternalPairs: []matcher.FieldPair{
			{
				Src:        loader.StructField{Name: "DisplayName", TypeStr: "string", ElemType: "string"},
				Dst:        loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				UseGetter:  true,
				GetterName: "GetDisplayName",
			},
		},
		Bidirectional: true,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)

	// ToExternal: direct access.
	assertContains(t, output, "dst.DisplayName = src.Name")

	// FromExternal: getter.
	assertContains(t, output, "dst.Name = src.GetDisplayName()")
}

func TestGenerateCross_PointerConversion(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:          "models",
		InternalType:         "Internal",
		ExternalType:         "External",
		ExternalPkgName:      "ext",
		ExternalPkgPath:      "github.com/org/repo/ext",
		ToExternalFuncName:   "MapInternalToExternal",
		FromExternalFuncName: "MapExternalToInternal",
		ToExternalPairs: []matcher.FieldPair{
			{
				// *string -> string (deref)
				Src: loader.StructField{Name: "Name", TypeStr: "*string", ElemType: "string", IsPtr: true},
				Dst: loader.StructField{Name: "FullName", TypeStr: "string", ElemType: "string", IsPtr: false},
			},
			{
				// int -> *int (addr)
				Src: loader.StructField{Name: "Value", TypeStr: "int", ElemType: "int", IsPtr: false},
				Dst: loader.StructField{Name: "Amount", TypeStr: "*int", ElemType: "int", IsPtr: true},
			},
		},
		FromExternalPairs: []matcher.FieldPair{
			{
				// string -> *string (addr)
				Src: loader.StructField{Name: "FullName", TypeStr: "string", ElemType: "string", IsPtr: false},
				Dst: loader.StructField{Name: "Name", TypeStr: "*string", ElemType: "string", IsPtr: true},
			},
			{
				// *int -> int (deref)
				Src: loader.StructField{Name: "Amount", TypeStr: "*int", ElemType: "int", IsPtr: true},
				Dst: loader.StructField{Name: "Value", TypeStr: "int", ElemType: "int", IsPtr: false},
			},
		},
		Bidirectional: true,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)

	// ToExternal: *string -> string should have nil check.
	assertContains(t, output, "src.Name != nil")
	assertContains(t, output, "dst.FullName = *src.Name")

	// ToExternal: int -> *int should take address.
	assertContains(t, output, "v := src.Value")

	// FromExternal: string -> *string should take address.
	assertContains(t, output, "v := src.FullName")

	// FromExternal: *int -> int should have nil check.
	assertContains(t, output, "src.Amount != nil")
	assertContains(t, output, "dst.Value = *src.Amount")
}

func TestGenerateCross_NoFromExternalPairs(t *testing.T) {
	// Test bidirectional with empty FromExternalPairs.
	ccfg := CrossConfig{
		PackageName:          "models",
		InternalType:         "User",
		ExternalType:         "UserProto",
		ExternalPkgName:      "pb",
		ExternalPkgPath:      "github.com/org/repo/proto",
		ToExternalFuncName:   "MapUserToUserProto",
		FromExternalFuncName: "MapUserProtoToUser",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
			},
		},
		FromExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
			},
		},
		Bidirectional: true,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)
	assertContains(t, output, "func MapUserToUserProto(src *User) *pb.UserProto")
	assertContains(t, output, "func MapUserProtoToUser(src *pb.UserProto) *User")
}

// --- Numeric cast tests ---

func TestGenerateMulti_NumericCast(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:         loader.StructField{Name: "Age", TypeStr: "int", ElemType: "int"},
					Dst:         loader.StructField{Name: "Age", TypeStr: "int32", ElemType: "int32"},
					NumericCast: true,
					CastType:    "int32",
				},
				{
					Src:         loader.StructField{Name: "Score", TypeStr: "float32", ElemType: "float32"},
					Dst:         loader.StructField{Name: "Score", TypeStr: "float64", ElemType: "float64"},
					NumericCast: true,
					CastType:    "float64",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "int32(src.Age)")
	assertContains(t, output, "float64(src.Score)")
}

func TestGenerateMulti_NumericCastPtrToVal(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:         loader.StructField{Name: "Count", TypeStr: "*int", ElemType: "int", IsPtr: true},
					Dst:         loader.StructField{Name: "Count", TypeStr: "int32", ElemType: "int32"},
					NumericCast: true,
					CastType:    "int32",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "src.Count != nil")
	assertContains(t, output, "int32(*src.Count)")
}

func TestGenerateMulti_ConverterFunc(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:           loader.StructField{Name: "Timestamp", TypeStr: "string", ElemType: "string"},
					Dst:           loader.StructField{Name: "Timestamp", TypeStr: "int64", ElemType: "int64"},
					ConverterFunc: "MapStringToInt64",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "MapStringToInt64(src.Timestamp)")
}

func TestGenerateMulti_Bidirectional(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	revCfg := Config{
		PackageName: "testdata",
		FuncName:    "MapBidiDestToBidiSource",
		SrcType:     "BidiDest",
		DstType:     "BidiSource",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
			},
			{
				Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				Dst: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
			},
		},
	}

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapBidiSourceToBidiDest",
			SrcType:     "BidiSource",
			DstType:     "BidiDest",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
					Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				},
				{
					Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
					Dst: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
		Bidirectional:   true,
		ReverseFunc:     &revCfg,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should contain both forward and reverse functions.
	assertContains(t, output, "func MapBidiSourceToBidiDest(src *BidiSource) *BidiDest")
	assertContains(t, output, "func MapBidiDestToBidiSource(src *BidiDest) *BidiSource")
}

// --- Enum / named type cast tests ---

func TestGenerateMulti_TypeCast_DirectAssignment(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			FuncName: "MapEnumSourceToEnumDest",
			SrcType:  "EnumSource",
			DstType:  "EnumDest",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{
						Name:               "Status",
						TypeStr:            "StatusA",
						ElemType:           "StatusA",
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "string",
					},
					Dst: loader.StructField{
						Name:               "Status",
						TypeStr:            "StatusB",
						ElemType:           "StatusB",
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "string",
					},
					TypeCast:     true,
					CastTypeName: "StatusB",
				},
				{
					Src: loader.StructField{
						Name:               "Role",
						TypeStr:            "RoleA",
						ElemType:           "RoleA",
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "int",
					},
					Dst: loader.StructField{
						Name:               "Role",
						TypeStr:            "RoleB",
						ElemType:           "RoleB",
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "int",
					},
					TypeCast:     true,
					CastTypeName: "RoleB",
				},
			},
		},
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "dst.Status = StatusB(src.Status)")
	assertContains(t, output, "dst.Role = RoleB(src.Role)")
}

func TestGenerateMulti_TypeCast_PtrSrcNonPtrDst(t *testing.T) {
	// *StatusA -> StatusB should generate nil-safe lambda.
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			FuncName: "MapPtrStatusAToStatusB",
			SrcType:  "SrcType",
			DstType:  "DstType",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{
						Name:               "Status",
						TypeStr:            "*StatusA",
						ElemType:           "StatusA",
						IsPtr:              true,
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "string",
					},
					Dst: loader.StructField{
						Name:               "Status",
						TypeStr:            "StatusB",
						ElemType:           "StatusB",
						IsPtr:              false,
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "string",
					},
					TypeCast:     true,
					CastTypeName: "StatusB",
				},
			},
		},
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// Should contain a nil check for the pointer source.
	assertContains(t, output, "src.Status != nil")
	assertContains(t, output, "StatusB(")
}

func TestGenerateMulti_TypeCast_NonPtrSrcPtrDst(t *testing.T) {
	// StatusA -> *StatusB should generate address-taking lambda.
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			FuncName: "MapStatusAToPtr",
			SrcType:  "SrcType",
			DstType:  "DstType",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{
						Name:               "Status",
						TypeStr:            "StatusA",
						ElemType:           "StatusA",
						IsPtr:              false,
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "string",
					},
					Dst: loader.StructField{
						Name:               "Status",
						TypeStr:            "*StatusB",
						ElemType:           "StatusB",
						IsPtr:              true,
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "string",
					},
					TypeCast:     true,
					CastTypeName: "StatusB",
				},
			},
		},
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// Should return &v pattern.
	assertContains(t, output, "*StatusB")
	assertContains(t, output, "return &v")
}

// --- renderCrossFunc new branches ---

func TestGenerateCross_NumericCast(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:        "models",
		InternalType:       "Local",
		ExternalType:       "Remote",
		ExternalPkgName:    "ext",
		ExternalPkgPath:    "example.com/ext",
		ToExternalFuncName: "MapLocalToRemote",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src:         loader.StructField{Name: "SmallID", TypeStr: "int32", ElemType: "int32"},
				Dst:         loader.StructField{Name: "BigID", TypeStr: "int64", ElemType: "int64"},
				NumericCast: true,
				CastType:    "int64",
			},
		},
		Bidirectional: false,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)
	assertContains(t, output, "int64(src.SmallID)")
}

func TestGenerateCross_TypeCast(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:        "models",
		InternalType:       "Local",
		ExternalType:       "Remote",
		ExternalPkgName:    "ext",
		ExternalPkgPath:    "example.com/ext",
		ToExternalFuncName: "MapLocalToRemote",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src:          loader.StructField{Name: "Status", TypeStr: "StatusA", ElemType: "StatusA", IsNamedNonStruct: true, UnderlyingTypeName: "string"},
				Dst:          loader.StructField{Name: "Status", TypeStr: "ext.StatusB", ElemType: "ext.StatusB", IsNamedNonStruct: true, UnderlyingTypeName: "string"},
				TypeCast:     true,
				CastTypeName: "ext.StatusB",
			},
		},
		Bidirectional: false,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)
	assertContains(t, output, "ext.StatusB(src.Status)")
}

func TestGenerateCross_ConverterFunc(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:        "models",
		InternalType:       "Local",
		ExternalType:       "Remote",
		ExternalPkgName:    "ext",
		ExternalPkgPath:    "example.com/ext",
		ToExternalFuncName: "MapLocalToRemote",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src:           loader.StructField{Name: "CreatedAt", TypeStr: "string", ElemType: "string"},
				Dst:           loader.StructField{Name: "CreatedAt", TypeStr: "int64", ElemType: "int64"},
				ConverterFunc: "ConvertTime",
			},
		},
		Bidirectional: false,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)
	assertContains(t, output, "ConvertTime(src.CreatedAt)")
}

// --- buildSliceMapping pointer element combinations ---

func TestGenerateMulti_SlicePtrElemToNonPtrElem(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapSrcToDst",
			SrcType:     "Src",
			DstType:     "Dst",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{
						Name:              "Items",
						TypeStr:           "[]*EmailInfo",
						IsSlice:           true,
						SliceElemIsPtr:    true,
						IsSliceElemStruct: true,
						SliceElemTypeName: "EmailInfo",
						SliceElemType:     "*EmailInfo",
					},
					Dst: loader.StructField{
						Name:              "Items",
						TypeStr:           "[]EmailInfoDTO",
						IsSlice:           true,
						SliceElemIsPtr:    false,
						IsSliceElemStruct: true,
						SliceElemTypeName: "EmailInfoDTO",
						SliceElemType:     "EmailInfoDTO",
					},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// Ptr-to-nonPtr slice element: nil check before deref, using nil-safe unwrap.
	assertContains(t, output, "if v != nil {")
	assertContains(t, output, "if r := MapEmailInfoToEmailInfoDTO(v); r != nil {")
}

func TestGenerateMulti_SliceNonPtrElemToPtrElem(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapSrcToDst",
			SrcType:     "Src",
			DstType:     "Dst",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{
						Name:              "Items",
						TypeStr:           "[]EmailInfo",
						IsSlice:           true,
						SliceElemIsPtr:    false,
						IsSliceElemStruct: true,
						SliceElemTypeName: "EmailInfo",
						SliceElemType:     "EmailInfo",
					},
					Dst: loader.StructField{
						Name:              "Items",
						TypeStr:           "[]*EmailInfoDTO",
						IsSlice:           true,
						SliceElemIsPtr:    true,
						IsSliceElemStruct: true,
						SliceElemTypeName: "EmailInfoDTO",
						SliceElemType:     "*EmailInfoDTO",
					},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// NonPtr-to-Ptr slice element: local item var + addr-of passed to mapper.
	assertContains(t, output, "item := v")
	assertContains(t, output, "dst.Items[i] = MapEmailInfoToEmailInfoDTO(&item)")
}

func TestGenerateMulti_SlicePtrElemToPtrElem(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapSrcToDst",
			SrcType:     "Src",
			DstType:     "Dst",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{
						Name:              "Items",
						TypeStr:           "[]*EmailInfo",
						IsSlice:           true,
						SliceElemIsPtr:    true,
						IsSliceElemStruct: true,
						SliceElemTypeName: "EmailInfo",
						SliceElemType:     "*EmailInfo",
					},
					Dst: loader.StructField{
						Name:              "Items",
						TypeStr:           "[]*EmailInfoDTO",
						IsSlice:           true,
						SliceElemIsPtr:    true,
						IsSliceElemStruct: true,
						SliceElemTypeName: "EmailInfoDTO",
						SliceElemType:     "*EmailInfoDTO",
					},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// Ptr-to-Ptr slice element: direct mapper call (ptr-in ptr-out).
	assertContains(t, output, "dst.Items[i] = MapEmailInfoToEmailInfoDTO(v)")
}

// --- buildConverterCall pointer combinations ---

func TestGenerateMulti_ConverterPtrSrcNonPtrDst(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:           loader.StructField{Name: "Field", TypeStr: "*string", ElemType: "string", IsPtr: true},
					Dst:           loader.StructField{Name: "Field", TypeStr: "int64", ElemType: "int64"},
					ConverterFunc: "MapStringToInt64",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// Ptr src, non-ptr dst: nil guard + deref call.
	assertContains(t, output, "src.Field != nil")
	assertContains(t, output, "MapStringToInt64(*src.Field)")
}

func TestGenerateMulti_ConverterNonPtrSrcPtrDst(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:           loader.StructField{Name: "Field", TypeStr: "string", ElemType: "string", IsPtr: false},
					Dst:           loader.StructField{Name: "Field", TypeStr: "*int64", ElemType: "int64", IsPtr: true},
					ConverterFunc: "MapStringToInt64",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// Non-ptr src, ptr dst: call converter + addr-of.
	assertContains(t, output, "MapStringToInt64(src.Field)")
	assertContains(t, output, "return &v")
}

func TestGenerateMulti_ConverterPtrSrcPtrDst(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:           loader.StructField{Name: "Field", TypeStr: "*string", ElemType: "string", IsPtr: true},
					Dst:           loader.StructField{Name: "Field", TypeStr: "*int64", ElemType: "int64", IsPtr: true},
					ConverterFunc: "MapStringToInt64",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// Ptr src, ptr dst: nil guard + deref call + addr-of.
	assertContains(t, output, "src.Field != nil")
	assertContains(t, output, "MapStringToInt64(*src.Field)")
	assertContains(t, output, "return &v")
}

// --- renderDelegated (struct_func delegation via multiGenerator) ---

func TestGenerateMulti_StructDelegation(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName:    "models",
			FuncName:       "MapSrcToDst",
			SrcType:        "Src",
			DstType:        "Dst",
			Pairs:          []matcher.FieldPair{},
			StructMapperFn: "CustomMapper",
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "func MapSrcToDst(src *Src) *Dst")
	assertContains(t, output, "v := Dst(CustomMapper(*src))")
	assertContains(t, output, "return &v")
}

// --- buildCastExpr ptr-to-ptr (NumericCast path) ---

func TestGenerateMulti_NumericCastPtrToPtr(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:         loader.StructField{Name: "Field", TypeStr: "*int32", ElemType: "int32", IsPtr: true},
					Dst:         loader.StructField{Name: "Field", TypeStr: "*int64", ElemType: "int64", IsPtr: true},
					NumericCast: true,
					CastType:    "int64",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// Ptr-to-ptr: nil guard + cast + addr-of.
	assertContains(t, output, "src.Field != nil")
	assertContains(t, output, "int64(*src.Field)")
	assertContains(t, output, "return &v")
}

// --- buildAssignmentMulti TypeCast branch (ptr-to-ptr) ---

func TestGenerateMulti_TypeCast_PtrToPtrDst(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			FuncName: "MapPtrStatusToPtrStatus",
			SrcType:  "SrcType",
			DstType:  "DstType",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{
						Name:               "Status",
						TypeStr:            "*StatusA",
						ElemType:           "StatusA",
						IsPtr:              true,
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "string",
					},
					Dst: loader.StructField{
						Name:               "Status",
						TypeStr:            "*StatusB",
						ElemType:           "StatusB",
						IsPtr:              true,
						IsNamedNonStruct:   true,
						UnderlyingTypeName: "string",
					},
					TypeCast:     true,
					CastTypeName: "StatusB",
				},
			},
		},
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// Ptr-to-ptr TypeCast: nil guard + cast + addr-of.
	assertContains(t, output, "src.Status != nil")
	assertContains(t, output, "StatusB(")
	assertContains(t, output, "return &v")
}

// --- Negative / edge case tests ---

func TestGenerateMulti_EmptyPairs(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapEmpty",
			SrcType:     "A",
			DstType:     "B",
			Pairs:       []matcher.FieldPair{},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "dst := &B{}")
	assertContains(t, output, "return dst")
}

func TestGenerateCross_NoBidi(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:          "models",
		InternalType:         "User",
		ExternalType:         "UserProto",
		ExternalPkgName:      "pb",
		ExternalPkgPath:      "github.com/org/repo/proto",
		ToExternalFuncName:   "MapUserToUserProto",
		FromExternalFuncName: "MapUserProtoToUser",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
			},
		},
		Bidirectional: false,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)
	assertContains(t, output, "func MapUserToUserProto(src *User) *pb.UserProto")
	// FromExternal function must NOT appear when Bidirectional=false.
	if strings.Contains(output, "MapUserProtoToUser") {
		t.Error("should not generate reverse function when Bidirectional=false")
	}
}

func TestGenerateCross_EmptyPairs(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:        "models",
		InternalType:       "User",
		ExternalType:       "UserProto",
		ExternalPkgName:    "pb",
		ExternalPkgPath:    "github.com/org/repo/proto",
		ToExternalFuncName: "MapUserToUserProto",
		ToExternalPairs:    []matcher.FieldPair{},
		Bidirectional:      false,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)
	assertContains(t, output, "func MapUserToUserProto(src *User) *pb.UserProto")
	assertContains(t, output, "return dst")
}

// --- renderCrossFunc HasCustomMapper branch ---

func TestGenerateCross_CustomMapperFn(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:        "models",
		InternalType:       "Local",
		ExternalType:       "Remote",
		ExternalPkgName:    "ext",
		ExternalPkgPath:    "example.com/ext",
		ToExternalFuncName: "MapLocalToRemote",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "CreatedAt", TypeStr: "time.Time", ElemType: "time.Time"},
				Dst: loader.StructField{Name: "CreatedAt", TypeStr: "string", ElemType: "string", MapperFn: "FormatTime"},
			},
		},
		Bidirectional: false,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)
	assertContains(t, output, "FormatTime(src.CreatedAt)")
}

// --- buildAssignmentMulti HasCustomMapper branch (explicit mapper fn, no ConverterFunc) ---

func TestGenerateMulti_CustomMapperFn(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{Name: "CreatedAt", TypeStr: "string", ElemType: "string"},
					Dst: loader.StructField{Name: "CreatedAt", TypeStr: "int64", ElemType: "int64", MapperFn: "ParseTimestamp"},
					// ConverterFunc is empty so the HasCustomMapper branch fires.
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "ParseTimestamp(src.CreatedAt)")
}

// --- buildAssignmentMulti DerefConversion and AddrConversion (plain pointer, no struct/slice/cast) ---

func TestGenerateMulti_DerefConversion(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{Name: "Name", TypeStr: "*string", ElemType: "string", IsPtr: true},
					Dst: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string", IsPtr: false},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "src.Name != nil")
	assertContains(t, output, "*src.Name")
}

func TestGenerateMulti_AddrConversion(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string", IsPtr: false},
					Dst: loader.StructField{Name: "Name", TypeStr: "*string", ElemType: "string", IsPtr: true},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "v := src.Name")
	assertContains(t, output, "return &v")
}

// --- buildNestedStructMapping !srcIsPtr && dstIsPtr branch ---

func TestGenerateMulti_NestedStructNonPtrToPtrDst(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapSrcToDst",
			SrcType:     "Src",
			DstType:     "Dst",
			Pairs: []matcher.FieldPair{
				{
					// Non-ptr Address src -> *AddressDTO dst.
					Src: loader.StructField{
						Name:          "Address",
						TypeStr:       "Address",
						ElemType:      "Address",
						IsPtr:         false,
						IsNamedStruct: true,
						StructName:    "Address",
					},
					Dst: loader.StructField{
						Name:          "Address",
						TypeStr:       "*AddressDTO",
						ElemType:      "AddressDTO",
						IsPtr:         true,
						IsNamedStruct: true,
						StructName:    "AddressDTO",
					},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	// NonPtr src -> Ptr dst: direct call with address-of src field.
	assertContains(t, output, "*AddressDTO")
	assertContains(t, output, "MapAddressToAddressDTO(&src.Address)")
}

func assertContains(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("output does not contain %q\n\nFull output:\n%s", needle, haystack)
	}
}
