package generator

import (
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/hacks1ash/goxmap/internal/loader"
	"github.com/hacks1ash/goxmap/internal/matcher"
)

func testdataDir(t *testing.T) string {
	t.Helper()
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot determine test file path")
	}
	// Navigate from internal/generator to internal/loader/testdata.
	return filepath.Join(filepath.Dir(filename), "..", "loader", "testdata")
}

func TestGenerate_DirectAssignment(t *testing.T) {
	cfg := Config{
		PackageName: "models",
		FuncName:    "MapUserToUserDTO",
		SrcType:     "User",
		DstType:     "UserDTO",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
			},
			{
				Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				Dst: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
			},
		},
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)

	assertContains(t, output, "// Code generated by mapper-gen; DO NOT EDIT.")
	assertContains(t, output, "package models")
	assertContains(t, output, "func MapUserToUserDTO(src User) UserDTO")
	assertContains(t, output, "dst.ID = src.ID")
	assertContains(t, output, "dst.Name = src.Name")
}

func TestGenerate_PointerDeref(t *testing.T) {
	cfg := Config{
		PackageName: "models",
		FuncName:    "MapAToB",
		SrcType:     "A",
		DstType:     "B",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "Value", TypeStr: "*string", ElemType: "string", IsPtr: true},
				Dst: loader.StructField{Name: "Value", TypeStr: "string", ElemType: "string", IsPtr: false},
			},
		},
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)
	assertContains(t, output, "src.Value != nil")
	assertContains(t, output, "*src.Value")
}

func TestGenerate_PointerAddr(t *testing.T) {
	cfg := Config{
		PackageName: "models",
		FuncName:    "MapAToB",
		SrcType:     "A",
		DstType:     "B",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "Value", TypeStr: "string", ElemType: "string", IsPtr: false},
				Dst: loader.StructField{Name: "Value", TypeStr: "*string", ElemType: "string", IsPtr: true},
			},
		},
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)
	assertContains(t, output, "v := src.Value")
	assertContains(t, output, "return &v")
}

func TestGenerate_CustomMapperFunc(t *testing.T) {
	cfg := Config{
		PackageName: "models",
		FuncName:    "MapAToB",
		SrcType:     "A",
		DstType:     "B",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "CreatedAt", TypeStr: "time.Time", ElemType: "time.Time"},
				Dst: loader.StructField{Name: "CreatedAt", TypeStr: "string", ElemType: "string", MapperFn: "FormatTime"},
			},
		},
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)
	assertContains(t, output, "dst.CreatedAt = FormatTime(src.CreatedAt)")
}

func TestGenerate_StructLevelMapper(t *testing.T) {
	cfg := Config{
		PackageName:    "models",
		FuncName:       "MapAToB",
		SrcType:        "A",
		DstType:        "B",
		StructMapperFn: "CustomMapAToB",
	}

	code, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	output := string(code)
	assertContains(t, output, "CustomMapAToB(src)")
}

func TestGenerateMulti_NestedStruct(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	srcInfo, err := loader.LoadStructFromPkg(pctx, "User")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(User): %v", err)
	}

	dstInfo, err := loader.LoadStructFromPkg(pctx, "UserDTO")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(UserDTO): %v", err)
	}

	result := matcher.Match(srcInfo, dstInfo)

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapUserToUserDTO",
			SrcType:     "User",
			DstType:     "UserDTO",
			Pairs:       result.Pairs,
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should contain the root mapper.
	assertContains(t, output, "func MapUserToUserDTO(src User) UserDTO")

	// Should contain a nested mapper for Address.
	assertContains(t, output, "func MapAddressToAddressDTO(src Address) AddressDTO")

	// Should contain a nested mapper for EmailInfo.
	assertContains(t, output, "func MapEmailInfoToEmailInfoDTO(src EmailInfo) EmailInfoDTO")

	// The root mapper should call the nested mappers.
	assertContains(t, output, "MapAddressToAddressDTO(src.Address)")

	// Should have a slice mapping loop for Emails.
	assertContains(t, output, "for i, v := range src.Emails")
	assertContains(t, output, "MapEmailInfoToEmailInfoDTO(v)")
}

func TestGenerateMulti_NestedPtrStruct(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	srcInfo, err := loader.LoadStructFromPkg(pctx, "UserWithPtr")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(UserWithPtr): %v", err)
	}

	dstInfo, err := loader.LoadStructFromPkg(pctx, "UserWithPtrDTO")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(UserWithPtrDTO): %v", err)
	}

	result := matcher.Match(srcInfo, dstInfo)

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapUserWithPtrToUserWithPtrDTO",
			SrcType:     "UserWithPtr",
			DstType:     "UserWithPtrDTO",
			Pairs:       result.Pairs,
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should handle *Address -> AddressDTO with nil check.
	assertContains(t, output, "src.Address != nil")
	assertContains(t, output, "MapAddressToAddressDTO(*src.Address)")
}

func TestGenerateMulti_MapperDiscovery(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	srcInfo, err := loader.LoadStructFromPkg(pctx, "User")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(User): %v", err)
	}

	dstInfo, err := loader.LoadStructFromPkg(pctx, "UserDTO")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(UserDTO): %v", err)
	}

	result := matcher.Match(srcInfo, dstInfo)

	// Simulate that MapAddressToAddressDTO already exists.
	existing := map[string]bool{
		"MapAddressToAddressDTO": true,
	}

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapUserToUserDTO",
			SrcType:     "User",
			DstType:     "UserDTO",
			Pairs:       result.Pairs,
		},
		ExistingMappers: existing,
		PkgContext:      pctx,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should still reference MapAddressToAddressDTO in the call.
	assertContains(t, output, "MapAddressToAddressDTO")

	// But should NOT generate a new MapAddressToAddressDTO function definition.
	if strings.Contains(output, "func MapAddressToAddressDTO") {
		t.Error("should not generate MapAddressToAddressDTO when it already exists in the package")
	}

	// Should still generate MapEmailInfoToEmailInfoDTO since it doesn't exist.
	assertContains(t, output, "func MapEmailInfoToEmailInfoDTO")
}

func TestGenerateMulti_CircularDependency(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	srcInfo, err := loader.LoadStructFromPkg(pctx, "Parent")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(Parent): %v", err)
	}

	dstInfo, err := loader.LoadStructFromPkg(pctx, "ParentDTO")
	if err != nil {
		t.Fatalf("LoadStructFromPkg(ParentDTO): %v", err)
	}

	result := matcher.Match(srcInfo, dstInfo)

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapParentToParentDTO",
			SrcType:     "Parent",
			DstType:     "ParentDTO",
			Pairs:       result.Pairs,
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
	}

	// This should NOT hang or panic due to circular references.
	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should contain both mapper functions.
	assertContains(t, output, "func MapParentToParentDTO(src Parent) ParentDTO")
	assertContains(t, output, "func MapChildToChildDTO(src Child) ChildDTO")

	// Should reference the child mapper from parent.
	assertContains(t, output, "MapChildToChildDTO")
	// Should reference the parent mapper from child.
	assertContains(t, output, "MapParentToParentDTO")
}

func TestGenerateMulti_SingleFunction(t *testing.T) {
	// Test that GenerateMulti works for a simple case with no nesting.
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
					Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "package models")
	assertContains(t, output, "func MapAToB(src A) B")
	assertContains(t, output, "dst.ID = src.ID")
}

// --- Cross-package generation tests ---

func TestGenerateCross_ToExternalOnly(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:        "models",
		InternalType:       "User",
		ExternalType:       "UserProto",
		ExternalPkgName:    "pb",
		ExternalPkgPath:    "github.com/org/repo/proto",
		ToExternalFuncName: "MapUserToUserProto",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "UserId", TypeStr: "int", ElemType: "int"},
			},
			{
				Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				Dst: loader.StructField{Name: "DisplayName", TypeStr: "string", ElemType: "string"},
			},
		},
		Bidirectional: false,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)

	assertContains(t, output, "// Code generated by mapper-gen; DO NOT EDIT.")
	assertContains(t, output, "package models")
	assertContains(t, output, `"github.com/org/repo/proto"`)
	assertContains(t, output, "func MapUserToUserProto(src User) pb.UserProto")
	assertContains(t, output, "dst.UserId = src.ID")
	assertContains(t, output, "dst.DisplayName = src.Name")

	// Should NOT contain a reverse function.
	if strings.Contains(output, "MapUserProtoToUser") {
		t.Error("should not generate reverse function when Bidirectional=false")
	}
}

func TestGenerateCross_Bidirectional(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:          "models",
		InternalType:         "User",
		ExternalType:         "UserProto",
		ExternalPkgName:      "pb",
		ExternalPkgPath:      "github.com/org/repo/proto",
		ToExternalFuncName:   "MapUserToUserProto",
		FromExternalFuncName: "MapUserProtoToUser",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "UserId", TypeStr: "int", ElemType: "int"},
			},
		},
		FromExternalPairs: []matcher.FieldPair{
			{
				Src:        loader.StructField{Name: "UserId", TypeStr: "int", ElemType: "int"},
				Dst:        loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				UseGetter:  true,
				GetterName: "GetUserId",
			},
		},
		Bidirectional: true,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)

	// Should contain both functions.
	assertContains(t, output, "func MapUserToUserProto(src User) pb.UserProto")
	assertContains(t, output, "func MapUserProtoToUser(src pb.UserProto) User")

	// ToExternal should use direct field access.
	assertContains(t, output, "dst.UserId = src.ID")

	// FromExternal should use getter.
	assertContains(t, output, "src.GetUserId()")
}

func TestGenerateCross_WithGetters(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:          "models",
		InternalType:         "User",
		ExternalType:         "UserProto",
		ExternalPkgName:      "pb",
		ExternalPkgPath:      "github.com/org/repo/proto",
		ToExternalFuncName:   "MapUserToUserProto",
		FromExternalFuncName: "MapUserProtoToUser",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				Dst: loader.StructField{Name: "DisplayName", TypeStr: "string", ElemType: "string"},
			},
		},
		FromExternalPairs: []matcher.FieldPair{
			{
				Src:        loader.StructField{Name: "DisplayName", TypeStr: "string", ElemType: "string"},
				Dst:        loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				UseGetter:  true,
				GetterName: "GetDisplayName",
			},
		},
		Bidirectional: true,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)

	// ToExternal: direct access.
	assertContains(t, output, "dst.DisplayName = src.Name")

	// FromExternal: getter.
	assertContains(t, output, "dst.Name = src.GetDisplayName()")
}

func TestGenerateCross_PointerConversion(t *testing.T) {
	ccfg := CrossConfig{
		PackageName:          "models",
		InternalType:         "Internal",
		ExternalType:         "External",
		ExternalPkgName:      "ext",
		ExternalPkgPath:      "github.com/org/repo/ext",
		ToExternalFuncName:   "MapInternalToExternal",
		FromExternalFuncName: "MapExternalToInternal",
		ToExternalPairs: []matcher.FieldPair{
			{
				// *string -> string (deref)
				Src: loader.StructField{Name: "Name", TypeStr: "*string", ElemType: "string", IsPtr: true},
				Dst: loader.StructField{Name: "FullName", TypeStr: "string", ElemType: "string", IsPtr: false},
			},
			{
				// int -> *int (addr)
				Src: loader.StructField{Name: "Value", TypeStr: "int", ElemType: "int", IsPtr: false},
				Dst: loader.StructField{Name: "Amount", TypeStr: "*int", ElemType: "int", IsPtr: true},
			},
		},
		FromExternalPairs: []matcher.FieldPair{
			{
				// string -> *string (addr)
				Src: loader.StructField{Name: "FullName", TypeStr: "string", ElemType: "string", IsPtr: false},
				Dst: loader.StructField{Name: "Name", TypeStr: "*string", ElemType: "string", IsPtr: true},
			},
			{
				// *int -> int (deref)
				Src: loader.StructField{Name: "Amount", TypeStr: "*int", ElemType: "int", IsPtr: true},
				Dst: loader.StructField{Name: "Value", TypeStr: "int", ElemType: "int", IsPtr: false},
			},
		},
		Bidirectional: true,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)

	// ToExternal: *string -> string should have nil check.
	assertContains(t, output, "src.Name != nil")
	assertContains(t, output, "dst.FullName = *src.Name")

	// ToExternal: int -> *int should take address.
	assertContains(t, output, "v := src.Value")

	// FromExternal: string -> *string should take address.
	assertContains(t, output, "v := src.FullName")

	// FromExternal: *int -> int should have nil check.
	assertContains(t, output, "src.Amount != nil")
	assertContains(t, output, "dst.Value = *src.Amount")
}

func TestGenerateCross_NoFromExternalPairs(t *testing.T) {
	// Test bidirectional with empty FromExternalPairs.
	ccfg := CrossConfig{
		PackageName:          "models",
		InternalType:         "User",
		ExternalType:         "UserProto",
		ExternalPkgName:      "pb",
		ExternalPkgPath:      "github.com/org/repo/proto",
		ToExternalFuncName:   "MapUserToUserProto",
		FromExternalFuncName: "MapUserProtoToUser",
		ToExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
			},
		},
		FromExternalPairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
			},
		},
		Bidirectional: true,
	}

	code, err := GenerateCross(ccfg)
	if err != nil {
		t.Fatalf("GenerateCross: %v", err)
	}

	output := string(code)
	assertContains(t, output, "func MapUserToUserProto(src User) pb.UserProto")
	assertContains(t, output, "func MapUserProtoToUser(src pb.UserProto) User")
}

// --- Numeric cast tests ---

func TestGenerateMulti_NumericCast(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:         loader.StructField{Name: "Age", TypeStr: "int", ElemType: "int"},
					Dst:         loader.StructField{Name: "Age", TypeStr: "int32", ElemType: "int32"},
					NumericCast: true,
					CastType:    "int32",
				},
				{
					Src:         loader.StructField{Name: "Score", TypeStr: "float32", ElemType: "float32"},
					Dst:         loader.StructField{Name: "Score", TypeStr: "float64", ElemType: "float64"},
					NumericCast: true,
					CastType:    "float64",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "int32(src.Age)")
	assertContains(t, output, "float64(src.Score)")
}

func TestGenerateMulti_NumericCastPtrToVal(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:         loader.StructField{Name: "Count", TypeStr: "*int", ElemType: "int", IsPtr: true},
					Dst:         loader.StructField{Name: "Count", TypeStr: "int32", ElemType: "int32"},
					NumericCast: true,
					CastType:    "int32",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "src.Count != nil")
	assertContains(t, output, "int32(*src.Count)")
}

func TestGenerateMulti_ConverterFunc(t *testing.T) {
	mcfg := MultiConfig{
		PackageName: "models",
		RootFunc: Config{
			PackageName: "models",
			FuncName:    "MapAToB",
			SrcType:     "A",
			DstType:     "B",
			Pairs: []matcher.FieldPair{
				{
					Src:           loader.StructField{Name: "Timestamp", TypeStr: "string", ElemType: "string"},
					Dst:           loader.StructField{Name: "Timestamp", TypeStr: "int64", ElemType: "int64"},
					ConverterFunc: "MapStringToInt64",
				},
			},
		},
		ExistingMappers: make(map[string]bool),
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)
	assertContains(t, output, "MapStringToInt64(src.Timestamp)")
}

func TestGenerateMulti_Bidirectional(t *testing.T) {
	dir := testdataDir(t)
	pctx, err := loader.LoadPackage(dir)
	if err != nil {
		t.Fatalf("LoadPackage: %v", err)
	}

	revCfg := Config{
		PackageName: "testdata",
		FuncName:    "MapBidiDestToBidiSource",
		SrcType:     "BidiDest",
		DstType:     "BidiSource",
		Pairs: []matcher.FieldPair{
			{
				Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
			},
			{
				Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				Dst: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
			},
		},
	}

	mcfg := MultiConfig{
		PackageName: "testdata",
		RootFunc: Config{
			PackageName: "testdata",
			FuncName:    "MapBidiSourceToBidiDest",
			SrcType:     "BidiSource",
			DstType:     "BidiDest",
			Pairs: []matcher.FieldPair{
				{
					Src: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
					Dst: loader.StructField{Name: "ID", TypeStr: "int", ElemType: "int"},
				},
				{
					Src: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
					Dst: loader.StructField{Name: "Name", TypeStr: "string", ElemType: "string"},
				},
			},
		},
		ExistingMappers: make(map[string]bool),
		PkgContext:      pctx,
		Bidirectional:   true,
		ReverseFunc:     &revCfg,
	}

	code, err := GenerateMulti(mcfg)
	if err != nil {
		t.Fatalf("GenerateMulti: %v", err)
	}

	output := string(code)

	// Should contain both forward and reverse functions.
	assertContains(t, output, "func MapBidiSourceToBidiDest(src BidiSource) BidiDest")
	assertContains(t, output, "func MapBidiDestToBidiSource(src BidiDest) BidiSource")
}

func assertContains(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("output does not contain %q\n\nFull output:\n%s", needle, haystack)
	}
}
