// Package generator produces Go source code for struct mapping functions
// using text/template. It supports nested struct mapping, slice mapping,
// mapper discovery/reuse, circular dependency protection, cross-package
// mapping with imports, bidirectional generation, and getter-based access.
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"github.com/hacks1ash/goxmap/internal/loader"
	"github.com/hacks1ash/goxmap/internal/matcher"
)

// Config holds all parameters needed to generate a mapping function.
type Config struct {
	PackageName    string
	FuncName       string
	SrcType        string
	DstType        string
	Pairs          []matcher.FieldPair
	StructMapperFn string // If set, delegate entire mapping to this function.
}

// MultiConfig holds all parameters needed for recursive multi-function generation.
type MultiConfig struct {
	PackageName string
	// RootFunc is the primary mapper requested by the user.
	RootFunc Config
	// ExistingMappers is the set of mapper function names already present in
	// the target package (discovered via loader.DiscoverMapperFuncs).
	ExistingMappers map[string]bool
	// PkgContext provides access to the loaded package for resolving nested types.
	PkgContext *loader.PackageContext

	// Bidirectional controls whether to also generate a reverse mapper.
	Bidirectional bool
	// ReverseFunc is the reverse mapper config (dst -> src) when Bidirectional is true.
	ReverseFunc *Config
}

// CrossConfig holds parameters for generating cross-package mapper functions.
type CrossConfig struct {
	PackageName string

	// InternalType is the local struct name (e.g. "User").
	InternalType string
	// ExternalType is the external struct name (e.g. "UserProto").
	ExternalType string
	// ExternalPkgName is the short package name for the external package (e.g. "pb").
	ExternalPkgName string
	// ExternalPkgPath is the full import path (e.g. "github.com/org/repo/proto").
	ExternalPkgPath string

	// ToExternalFuncName is the name of the internal->external function.
	ToExternalFuncName string
	// FromExternalFuncName is the name of the external->internal function.
	FromExternalFuncName string

	// ToExternalPairs are field pairs for internal->external mapping.
	ToExternalPairs []matcher.FieldPair
	// FromExternalPairs are field pairs for external->internal mapping.
	FromExternalPairs []matcher.FieldPair

	// Bidirectional controls whether to generate both directions.
	Bidirectional bool
}

// funcEntry represents a single mapper function to generate.
type funcEntry struct {
	FuncName       string
	SrcType        string
	DstType        string
	Pairs          []matcher.FieldPair
	StructMapperFn string
}

// GenerateMulti produces formatted Go source code containing all required
// mapper functions, including recursively discovered nested struct mappers
// and slice element mappers. It uses circular dependency protection to
// prevent infinite loops.
func GenerateMulti(mcfg MultiConfig) ([]byte, error) {
	gen := &multiGenerator{
		pkgName:    mcfg.PackageName,
		existing:   mcfg.ExistingMappers,
		pctx:       mcfg.PkgContext,
		inProgress: make(map[string]bool),
		generated:  make(map[string]bool),
	}

	if gen.existing == nil {
		gen.existing = make(map[string]bool)
	}

	root := funcEntry{
		FuncName:       mcfg.RootFunc.FuncName,
		SrcType:        mcfg.RootFunc.SrcType,
		DstType:        mcfg.RootFunc.DstType,
		Pairs:          mcfg.RootFunc.Pairs,
		StructMapperFn: mcfg.RootFunc.StructMapperFn,
	}

	if err := gen.enqueue(root); err != nil {
		return nil, err
	}

	// Enqueue reverse mapper if bidirectional mode is enabled.
	if mcfg.Bidirectional && mcfg.ReverseFunc != nil {
		rev := funcEntry{
			FuncName:       mcfg.ReverseFunc.FuncName,
			SrcType:        mcfg.ReverseFunc.SrcType,
			DstType:        mcfg.ReverseFunc.DstType,
			Pairs:          mcfg.ReverseFunc.Pairs,
			StructMapperFn: mcfg.ReverseFunc.StructMapperFn,
		}
		if err := gen.enqueue(rev); err != nil {
			return nil, err
		}
	}

	return gen.render()
}

// Generate produces formatted Go source code for a single mapper function.
// This is the backward-compatible entry point.
func Generate(cfg Config) ([]byte, error) {
	if cfg.StructMapperFn != "" {
		return generateDelegated(cfg)
	}
	return generateFieldLevel(cfg)
}

// GenerateCross produces formatted Go source code for cross-package mapping.
// It generates one or two functions depending on the Bidirectional flag,
// with proper import statements for the external package.
func GenerateCross(ccfg CrossConfig) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprint(&buf, "// Code generated by goxmap; DO NOT EDIT.\n\n")
	fmt.Fprint(&buf, "package "+ccfg.PackageName+"\n\n")

	// Emit import block for the external package.
	fmt.Fprint(&buf, "import (\n")
	fmt.Fprintf(&buf, "\t%q\n", ccfg.ExternalPkgPath)
	fmt.Fprint(&buf, ")\n\n")

	extQualified := ccfg.ExternalPkgName + "." + ccfg.ExternalType

	// Generate internal -> external (ToExternal).
	renderCrossFunc(&buf, ccfg.ToExternalFuncName,
		ccfg.InternalType, extQualified,
		ccfg.ToExternalPairs, false)

	// Generate external -> internal (FromExternal) if bidirectional.
	if ccfg.Bidirectional && ccfg.FromExternalFuncName != "" {
		buf.WriteString("\n")
		renderCrossFunc(&buf, ccfg.FromExternalFuncName,
			extQualified, ccfg.InternalType,
			ccfg.FromExternalPairs, true)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w (raw output:\n%s)", err, buf.String())
	}

	return formatted, nil
}

// renderCrossFunc writes a single cross-package mapping function to buf.
// When useGetters is true and a pair has UseGetter set, it reads from the
// source using the getter method instead of direct field access.
func renderCrossFunc(buf *bytes.Buffer, funcName, srcType, dstType string, pairs []matcher.FieldPair, useGetters bool) {
	fmt.Fprintf(buf, "// %s maps %s to %s.\n", funcName, srcType, dstType)
	fmt.Fprintf(buf, "func %s(src *%s) *%s {\n", funcName, srcType, dstType)
	fmt.Fprintf(buf, "\tif src == nil { return nil }\n")
	fmt.Fprintf(buf, "\tdst := &%s{}\n", dstType)

	for _, pair := range pairs {
		srcExpr := "src." + pair.Src.Name

		// Use getter if available and we are reading from external struct.
		// Skip getter when it returns a value type but the destination needs
		// a pointer — direct field access preserves nil semantics.
		useGetter := useGetters && pair.UseGetter && pair.GetterName != "" &&
			(!pair.Src.IsPtr || pair.GetterReturnsPtr || !pair.Dst.IsPtr)
		if useGetter {
			srcExpr = "src." + pair.GetterName + "()"
		}

		if pair.HasCustomMapper() {
			fmt.Fprintf(buf, "\tdst.%s = %s(%s)\n", pair.Dst.Name, pair.Dst.MapperFn, srcExpr)
			continue
		}

		// Converter function (auto-discovered or from tag).
		if pair.ConverterFunc != "" {
			fmt.Fprintf(buf, "\tdst.%s = %s(%s)\n", pair.Dst.Name, pair.ConverterFunc, srcExpr)
			continue
		}

		// Numeric cast (e.g., int32 -> int64).
		if pair.NumericCast {
			fmt.Fprintf(buf, "\tdst.%s = %s(%s)\n", pair.Dst.Name, pair.CastType, srcExpr)
			continue
		}

		// Named type cast (e.g., StatusA -> StatusB).
		if pair.TypeCast {
			fmt.Fprintf(buf, "\tdst.%s = %s(%s)\n", pair.Dst.Name, pair.CastTypeName, srcExpr)
			continue
		}

		conv := pair.Conversion()

		// When using a getter that returns a value type for a pointer field
		// (e.g., proto GetCountry() string for Country *string), adjust the
		// conversion since the getter already strips the pointer.
		if useGetter && pair.Src.IsPtr && !pair.GetterReturnsPtr {
			if conv == matcher.DerefConversion { // *T → T, but getter gives T → T
				conv = matcher.NoneConversion
			}
		}

		switch conv {
		case matcher.NoneConversion:
			fmt.Fprintf(buf, "\tdst.%s = %s\n", pair.Dst.Name, srcExpr)
		case matcher.DerefConversion:
			fmt.Fprintf(buf, "\tif %s != nil {\n", srcExpr)
			fmt.Fprintf(buf, "\t\tdst.%s = *%s\n", pair.Dst.Name, srcExpr)
			fmt.Fprintf(buf, "\t}\n")
		case matcher.AddrConversion:
			elemType := pair.Src.ElemType
			if pair.Dst.ElemType != "" {
				elemType = pair.Dst.ElemType
			}
			fmt.Fprintf(buf, "\tdst.%s = func() *%s { v := %s; return &v }()\n",
				pair.Dst.Name, elemType, srcExpr)
		}
	}

	fmt.Fprintf(buf, "\treturn dst\n")
	fmt.Fprintf(buf, "}\n")
}

// multiGenerator orchestrates recursive mapper generation.
type multiGenerator struct {
	pkgName    string
	existing   map[string]bool
	pctx       *loader.PackageContext
	inProgress map[string]bool
	generated  map[string]bool
	funcs      []funcEntry
}

func (g *multiGenerator) enqueue(entry funcEntry) error {
	key := entry.FuncName
	if g.generated[key] || g.existing[key] {
		return nil
	}
	if g.inProgress[key] {
		return nil
	}

	g.inProgress[key] = true
	defer delete(g.inProgress, key)

	g.generated[key] = true

	if entry.StructMapperFn == "" {
		for _, pair := range entry.Pairs {
			if err := g.processFieldPair(pair); err != nil {
				return fmt.Errorf("processing field %s: %w", pair.Dst.Name, err)
			}
		}
	}

	g.funcs = append(g.funcs, entry)
	return nil
}

func (g *multiGenerator) processFieldPair(pair matcher.FieldPair) error {
	if pair.HasCustomMapper() {
		return nil
	}

	if pair.NeedsNestedMapper() {
		return g.ensureMapper(pair.Src.StructName, pair.Dst.StructName)
	}

	if pair.NeedsSliceMapper() {
		srcElem := pair.Src.SliceElemTypeName
		dstElem := pair.Dst.SliceElemTypeName
		return g.ensureMapper(srcElem, dstElem)
	}

	return nil
}

func (g *multiGenerator) ensureMapper(srcType, dstType string) error {
	funcName := "Map" + srcType + "To" + dstType
	if g.generated[funcName] || g.existing[funcName] {
		return nil
	}

	if g.pctx == nil {
		return nil
	}

	srcInfo, err := loader.LoadStructFromPkg(g.pctx, srcType)
	if err != nil {
		return fmt.Errorf("loading nested source type %s: %w", srcType, err)
	}

	dstInfo, err := loader.LoadStructFromPkg(g.pctx, dstType)
	if err != nil {
		return fmt.Errorf("loading nested destination type %s: %w", dstType, err)
	}

	result := matcher.Match(srcInfo, dstInfo, matcher.MatchOptions{})

	entry := funcEntry{
		FuncName:       funcName,
		SrcType:        srcType,
		DstType:        dstType,
		Pairs:          result.Pairs,
		StructMapperFn: dstInfo.MapperFunc,
	}

	return g.enqueue(entry)
}

func (g *multiGenerator) render() ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by goxmap; DO NOT EDIT.\n\n")
	buf.WriteString("package " + g.pkgName + "\n\n")

	for i, entry := range g.funcs {
		if i > 0 {
			buf.WriteString("\n")
		}

		body, err := g.renderFunc(entry)
		if err != nil {
			return nil, fmt.Errorf("rendering %s: %w", entry.FuncName, err)
		}
		buf.Write(body)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w (raw output:\n%s)", err, buf.String())
	}

	return formatted, nil
}

func (g *multiGenerator) renderFunc(entry funcEntry) ([]byte, error) {
	if entry.StructMapperFn != "" {
		return g.renderDelegated(entry)
	}
	return g.renderFieldLevel(entry)
}

func (g *multiGenerator) renderDelegated(entry funcEntry) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// %s maps %s to %s using a custom mapper function.\n",
		entry.FuncName, entry.SrcType, entry.DstType)
	fmt.Fprintf(&buf, "func %s(src *%s) *%s {\n", entry.FuncName, entry.SrcType, entry.DstType)
	fmt.Fprintf(&buf, "\tif src == nil { return nil }\n")
	fmt.Fprintf(&buf, "\tv := %s(%s(*src))\n", entry.DstType, entry.StructMapperFn)
	fmt.Fprintf(&buf, "\treturn &v\n")
	fmt.Fprintf(&buf, "}\n")
	return buf.Bytes(), nil
}

func (g *multiGenerator) renderFieldLevel(entry funcEntry) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// %s maps %s to %s.\n",
		entry.FuncName, entry.SrcType, entry.DstType)
	fmt.Fprintf(&buf, "func %s(src *%s) *%s {\n", entry.FuncName, entry.SrcType, entry.DstType)
	fmt.Fprintf(&buf, "\tif src == nil { return nil }\n")
	fmt.Fprintf(&buf, "\tdst := &%s{}\n", entry.DstType)

	for _, pair := range entry.Pairs {
		expr, err := g.buildAssignmentMulti(pair)
		if err != nil {
			return nil, fmt.Errorf("building assignment for %s: %w", pair.Dst.Name, err)
		}

		if strings.Contains(expr, "\n") {
			for _, line := range strings.Split(expr, "\n") {
				fmt.Fprintf(&buf, "%s\n", line)
			}
		} else {
			fmt.Fprintf(&buf, "\tdst.%s = %s\n", pair.Dst.Name, expr)
		}
	}

	fmt.Fprintf(&buf, "\treturn dst\n")
	fmt.Fprintf(&buf, "}\n")
	return buf.Bytes(), nil
}

func (g *multiGenerator) buildAssignmentMulti(pair matcher.FieldPair) (string, error) {
	srcExpr := "src." + pair.Src.Name

	// Custom mapper func tag (explicit mapper:"func:...") takes highest priority.
	if pair.HasCustomMapper() && pair.ConverterFunc == "" {
		return pair.Dst.MapperFn + "(" + srcExpr + ")", nil
	}

	// Converter function (either from tag or auto-discovered).
	if pair.ConverterFunc != "" {
		return g.buildConverterCall(pair, srcExpr), nil
	}

	// Numeric cast.
	if pair.NumericCast {
		return g.buildNumericCast(pair, srcExpr), nil
	}

	// Named type cast (enum support).
	if pair.TypeCast {
		return g.buildTypeCast(pair, srcExpr), nil
	}

	if pair.NeedsSliceMapper() {
		return g.buildSliceMapping(pair, srcExpr), nil
	}

	if pair.NeedsNestedMapper() {
		return g.buildNestedStructMapping(pair, srcExpr), nil
	}

	switch pair.Conversion() {
	case matcher.NoneConversion:
		return srcExpr, nil
	case matcher.DerefConversion:
		return buildDeref(pair.Src, srcExpr), nil
	case matcher.AddrConversion:
		return buildAddr(pair.Src, srcExpr), nil
	default:
		return "", fmt.Errorf("unknown conversion type for field %s", pair.Dst.Name)
	}
}

// buildCastExpr generates an inline type cast expression with pointer handling.
// Used for both numeric casts (int -> int32) and named type casts (StatusA -> StatusB).
func (g *multiGenerator) buildCastExpr(castType string, pair matcher.FieldPair, srcExpr string) string {
	srcIsPtr := pair.Src.IsPtr
	dstIsPtr := pair.Dst.IsPtr

	switch {
	case !srcIsPtr && !dstIsPtr:
		return fmt.Sprintf("%s(%s)", castType, srcExpr)

	case srcIsPtr && !dstIsPtr:
		return fmt.Sprintf(
			"func() %s { if %s != nil { return %s(*%s) }; var zero %s; return zero }()",
			castType, srcExpr, castType, srcExpr, castType,
		)

	case !srcIsPtr && dstIsPtr:
		return fmt.Sprintf(
			"func() *%s { v := %s(%s); return &v }()",
			castType, castType, srcExpr,
		)

	default:
		return fmt.Sprintf(
			"func() *%s { if %s != nil { v := %s(*%s); return &v }; return nil }()",
			castType, srcExpr, castType, srcExpr,
		)
	}
}

// buildNumericCast generates a numeric type cast expression (e.g., int -> int32).
func (g *multiGenerator) buildNumericCast(pair matcher.FieldPair, srcExpr string) string {
	return g.buildCastExpr(pair.CastType, pair, srcExpr)
}

// buildTypeCast generates a named type cast expression (e.g., StatusA -> StatusB).
func (g *multiGenerator) buildTypeCast(pair matcher.FieldPair, srcExpr string) string {
	return g.buildCastExpr(pair.CastTypeName, pair, srcExpr)
}

// buildConverterCall generates a converter function call expression, handling
// pointer combinations on the source side.
func (g *multiGenerator) buildConverterCall(pair matcher.FieldPair, srcExpr string) string {
	fn := pair.ConverterFunc
	srcIsPtr := pair.Src.IsPtr
	dstIsPtr := pair.Dst.IsPtr

	switch {
	case !srcIsPtr && !dstIsPtr:
		return fmt.Sprintf("%s(%s)", fn, srcExpr)

	case srcIsPtr && !dstIsPtr:
		return fmt.Sprintf(
			"func() %s { if %s != nil { return %s(*%s) }; var zero %s; return zero }()",
			pair.Dst.ElemType, srcExpr, fn, srcExpr, pair.Dst.ElemType,
		)

	case !srcIsPtr && dstIsPtr:
		return fmt.Sprintf(
			"func() *%s { v := %s(%s); return &v }()",
			pair.Dst.ElemType, fn, srcExpr,
		)

	default:
		return fmt.Sprintf(
			"func() *%s { if %s != nil { v := %s(*%s); return &v }; return nil }()",
			pair.Dst.ElemType, srcExpr, fn, srcExpr,
		)
	}
}

func (g *multiGenerator) buildNestedStructMapping(pair matcher.FieldPair, srcExpr string) string {
	mapperFn := "Map" + pair.Src.StructName + "To" + pair.Dst.StructName

	srcIsPtr := pair.Src.IsPtr
	dstIsPtr := pair.Dst.IsPtr

	switch {
	case !srcIsPtr && !dstIsPtr:
		// Safe to deref: &src.Field is never nil (src itself is nil-guarded), so mapper always returns non-nil.
		return fmt.Sprintf("*%s(&%s)", mapperFn, srcExpr)

	case srcIsPtr && !dstIsPtr:
		// src field is a pointer: pass directly to mapper, deref the *T result to T
		return fmt.Sprintf(
			"func() %s { if v := %s(%s); v != nil { return *v }; var zero %s; return zero }()",
			pair.Dst.StructName, mapperFn, srcExpr, pair.Dst.StructName,
		)

	case !srcIsPtr && dstIsPtr:
		// src field is a value: take address to pass to mapper, result is *T (what dst wants)
		return fmt.Sprintf("%s(&%s)", mapperFn, srcExpr)

	default:
		// src field is a pointer: pass directly, mapper handles nil, result is *T (what dst wants)
		return fmt.Sprintf("%s(%s)", mapperFn, srcExpr)
	}
}

func (g *multiGenerator) buildSliceMapping(pair matcher.FieldPair, srcExpr string) string {
	mapperFn := "Map" + pair.Src.SliceElemTypeName + "To" + pair.Dst.SliceElemTypeName

	dstElemType := pair.Dst.SliceElemTypeName
	if pair.Dst.SliceElemIsPtr {
		dstElemType = "*" + dstElemType
	}

	var b strings.Builder

	fmt.Fprintf(&b, "\tif %s != nil {\n", srcExpr)
	fmt.Fprintf(&b, "\t\tdst.%s = make([]%s, len(%s))\n", pair.Dst.Name, dstElemType, srcExpr)
	fmt.Fprintf(&b, "\t\tfor i, v := range %s {\n", srcExpr)

	srcElemIsPtr := pair.Src.SliceElemIsPtr
	dstElemIsPtr := pair.Dst.SliceElemIsPtr

	switch {
	case !srcElemIsPtr && !dstElemIsPtr:
		// v is a value elem: need addressable temp to pass as *T; deref *T result to T
		fmt.Fprintf(&b, "\t\t\titem := v\n")
		fmt.Fprintf(&b, "\t\t\tdst.%s[i] = *%s(&item)\n", pair.Dst.Name, mapperFn)

	case srcElemIsPtr && !dstElemIsPtr:
		// v is already *T: pass directly to mapper; mapper returns *T, deref to T
		fmt.Fprintf(&b, "\t\t\tif v != nil {\n")
		fmt.Fprintf(&b, "\t\t\t\tif r := %s(v); r != nil {\n", mapperFn)
		fmt.Fprintf(&b, "\t\t\t\t\tdst.%s[i] = *r\n", pair.Dst.Name)
		fmt.Fprintf(&b, "\t\t\t\t}\n")
		fmt.Fprintf(&b, "\t\t\t}\n")

	case !srcElemIsPtr && dstElemIsPtr:
		// v is a value elem: addressable temp; mapper returns *T which is what dst wants
		fmt.Fprintf(&b, "\t\t\titem := v\n")
		fmt.Fprintf(&b, "\t\t\tdst.%s[i] = %s(&item)\n", pair.Dst.Name, mapperFn)

	default:
		// v is already *T: pass directly; mapper handles nil and returns *T
		fmt.Fprintf(&b, "\t\t\tdst.%s[i] = %s(v)\n", pair.Dst.Name, mapperFn)
	}

	fmt.Fprint(&b, "\t\t}\n")
	fmt.Fprint(&b, "\t}")

	return b.String()
}

type templateData struct {
	PackageName string
	FuncName    string
	SrcType     string
	DstType     string
	Assignments []assignmentData
}

type assignmentData struct {
	DstField   string
	Expression string
}

func generateFieldLevel(cfg Config) ([]byte, error) {
	assignments := make([]assignmentData, 0, len(cfg.Pairs))

	for _, pair := range cfg.Pairs {
		expr, err := buildAssignment(pair)
		if err != nil {
			return nil, fmt.Errorf("building assignment for %s: %w", pair.Dst.Name, err)
		}
		assignments = append(assignments, assignmentData{
			DstField:   pair.Dst.Name,
			Expression: expr,
		})
	}

	data := templateData{
		PackageName: cfg.PackageName,
		FuncName:    cfg.FuncName,
		SrcType:     cfg.SrcType,
		DstType:     cfg.DstType,
		Assignments: assignments,
	}

	return executeTemplate(fieldLevelTmpl, data)
}

func generateDelegated(cfg Config) ([]byte, error) {
	data := templateData{
		PackageName: cfg.PackageName,
		FuncName:    cfg.FuncName,
		SrcType:     cfg.SrcType,
		DstType:     cfg.DstType,
	}

	tmplText := `// Code generated by goxmap; DO NOT EDIT.

package {{ .PackageName }}

// {{ .FuncName }} maps {{ .SrcType }} to {{ .DstType }} using a custom mapper function.
func {{ .FuncName }}(src *{{ .SrcType }}) *{{ .DstType }} {
	if src == nil { return nil }
	v := {{ .DstType }}(` + cfg.StructMapperFn + `(*src))
	return &v
}
`
	return executeTemplate(tmplText, data)
}

const fieldLevelTmpl = `// Code generated by goxmap; DO NOT EDIT.

package {{ .PackageName }}

// {{ .FuncName }} maps {{ .SrcType }} to {{ .DstType }}.
func {{ .FuncName }}(src *{{ .SrcType }}) *{{ .DstType }} {
	if src == nil { return nil }
	dst := &{{ .DstType }}{}
{{- range .Assignments }}
	dst.{{ .DstField }} = {{ .Expression }}
{{- end }}
	return dst
}
`

func buildAssignment(pair matcher.FieldPair) (string, error) {
	srcExpr := "src." + pair.Src.Name

	if pair.HasCustomMapper() {
		return pair.Dst.MapperFn + "(" + srcExpr + ")", nil
	}

	switch pair.Conversion() {
	case matcher.NoneConversion:
		return srcExpr, nil

	case matcher.DerefConversion:
		return buildDeref(pair.Src, srcExpr), nil

	case matcher.AddrConversion:
		return buildAddr(pair.Src, srcExpr), nil

	default:
		return "", fmt.Errorf("unknown conversion type for field %s", pair.Dst.Name)
	}
}

func buildDeref(src loader.StructField, srcExpr string) string {
	return fmt.Sprintf(
		"func() %s { if %s != nil { return *%s }; var zero %s; return zero }()",
		src.ElemType, srcExpr, srcExpr, src.ElemType,
	)
}

func buildAddr(src loader.StructField, srcExpr string) string {
	return fmt.Sprintf(
		"func() *%s { v := %s; return &v }()",
		src.ElemType, srcExpr,
	)
}

func executeTemplate(tmplText string, data templateData) ([]byte, error) {
	t, err := template.New("mapper").Parse(tmplText)
	if err != nil {
		return nil, fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated code: %w (raw output:\n%s)", err, buf.String())
	}

	return formatted, nil
}
