// Code generated by goxmap; DO NOT EDIT.

package main

import (
	"github.com/hacks1ash/goxmap/_examples/02-protobuf-integration/pb"
)

// MapUserToPbUser maps User to pb.User.
func MapUserToPbUser(src *User) *pb.User {
	if src == nil {
		return nil
	}
	dst := &pb.User{}
	dst.UserId = src.ID
	dst.FullName = src.Name
	dst.UserEmail = src.Email
	dst.UserAge = src.Age
	return dst
}

// MapPbUserToUser maps pb.User to User.
func MapPbUserToUser(src *pb.User) *User {
	if src == nil {
		return nil
	}
	dst := &User{}
	dst.ID = src.GetUserId()
	dst.Name = src.GetFullName()
	dst.Email = src.GetUserEmail()
	dst.Age = src.GetUserAge()
	return dst
}
